blogApp/article/urls.py
from django.urls import path
from . import views
app_name = 'article'

urlpatterns = [
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('article-safe-delete/<int:id>',views.article_safe_delete,name="article_safe_delete"),
    path('article-create/',views.article_create,name="article_create"),
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail')
]

blogApp/blogApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('edit/<int:id>/',views.profile_edit,name="edit"),
    path('delete/<int:id>',views.user_delete,name="delete"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('register/',views.user_register,name="register")
]

blogApp/templates/base.html
<!-- 载入静态文件 -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    {% include 'header.html' %}
    {% block content %}{% endblock content %}
    {% include 'footer.html' %}
<script src="{% static 'jQuery/jquery-3.3.1.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
<script src="{% static 'popper/popper-1.14.4.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

blogApp/templates/footer.html
{% load static %}
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

blogApp/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">我的博客</a>
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">
                        写文章
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">
                        文章
                    </a>
                </li>
                {% if user.is_authenticated %}
                <!-- 如果用户已经登录，显示用户名下拉框 -->
                <form 
                    style="display:none"
                    id="user_delete"
                    action="{% url 'userprofile:delete' user.id %}"
                    method="POST"
                >
                {% csrf_token %}
                <button type="submit">发送</button>
                </form>
                <script>
                    function user_delete(){
                        layer.open({
                            title:'确认删除',
                            content:'确认删除用户资料吗？',
                            yes:function(index,layero){
                                $('form#user_delete button').click()
                                layer.close(index)
                            }
                        })
                
                    }
                </script>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{user.username}}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">个人信息</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                            <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                        </div>
                    </li>
                {% else %}
                <!-- 如果未登录，显示登录 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>