blogApp/article/urls.py
from django.urls import path
from . import views
app_name = 'article'

urlpatterns = [
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('article-safe-delete/<int:id>',views.article_safe_delete,name="article_safe_delete"),
    path('article-create/',views.article_create,name="article_create"),
    path('article-list/',views.article_list,name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail')
]

blogApp/blogApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/',views.post_comment,name="post_comment")
]

blogApp/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('edit/<int:id>/',views.profile_edit,name="edit"),
    path('delete/<int:id>',views.user_delete,name="delete"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('register/',views.user_register,name="register")
]

blogApp/article/models.py
# -*-coding:utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from PIL import Image

# Create your models here.
class ArticleColumn(models.Model):
    """
    栏目的Model
    """
    # 栏目标题
    title = models.CharField(max_length=100,blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章栏目的一对多外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )
    title = models.CharField(max_length=100)
    body = models.TextField()
    # 创建时间
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    # 文章浏览量
    total_views = models.PositiveIntegerField(default=0)
    # 文章标签
    tags  = TaggableManager(blank=True)
    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d',blank=True)

    # 内部类Meta，用于给model定义元数据
    class Meta:
        # ordering指定返回的数据排列顺序
        # 按时间倒序
        ordering = ('-created',)


    def __str__(self):
        return self.title
    
    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id])
    
    
    def save(self,*args,**kwargs):
        # 调用原有的save()功能
        article = super(ArticlePost,self).save(*args,**kwargs)
        # 固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            image  = Image.open(self.avatar)
            (x,y) = image.size
            new_x = 400
            new_y = int(new_x*(y/x))
            resized_image = image.resize((new_x,new_y),Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article

blogApp/article/forms.py
from django import forms
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body','tags','avatar')

blogApp/article/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import ArticlePost,ArticleColumn
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
import markdown
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm

# Create your views here.
def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()
    # 用户搜索逻辑
    if search:
        if order == 'total_views':
            # 用Q对象进行联合搜索
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search)|
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search)|
                Q(body__icontains=search)
            )
    else:
        # 
        search = ''
    
    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.update_fields(column=column)
    
    # 标签查询集
    if tag and tag !='None':
        article_list = article_list.filter(tags__name__in=[tag])
    
    # 查询集排序
    if order == 'total_view':
        article_list = ArticlePost.objects.all().order_by('-title_views')

    # 每页显示一篇文章
    paginator = Paginator(article_list,3)
    # 获取url中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给articles
    articles = paginator.get_page(page)
    # 需要传递给模板的对象
    context = {'articles':articles,
    'order':order,
    'search':search,
    'column':column,
    'tag':tag
    }
    # render函数：传递给模板，并返回对象
    return render(request,'article/list.html',context)

# 文章详情
def article_detail(request,id):
    article = ArticlePost.objects.get(id=id)
    # 取出评论
    comments = Comment.objects.filter(article=id)
    comment_form = CommentForm()
    # 浏览量加一
    article.total_views += 1
    article.save(update_fields=['total_views'])
    md = markdown.Markdown(
        # 包含缩写、表格等常用扩展
       extensions = ['markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        # 锚点目录
        'markdown.extensions.toc'
       ])
    article.body = md.convert(article.body)
    context = {
        'article':article,
        'toc':md.toc,
        'comments':comments,
        # 引入评论表单
        'comment_form':comment_form
        }
    return render(request,'article/detail.html',context)

# 写文章的视图
def article_create(request):
    # 判断用户是否提交数据
    if request.method == 'POST':
        # 将提交的数据赋值给表单实例
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        # 判断提交的数据是否满足模型的要求
        if(article_post_form.is_valid):
            # 保存数据，但不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定目前登录的用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            # 保存栏目
            if request.POST['column']!='none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            # 文章保存到数据库中
            new_article.save()
            # 保存tags的多对多关系
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 获得栏目选项
        columns = ArticleColumn.objects.all()
        # 赋值上下文
        context = {'article_post_form':article_post_form,'columns':columns}
        # 返回模板
        return render(request,'article/create.html',context)

# 文章删除(安全)
def article_safe_delete(request,id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")

# 文章更新
@login_required(login_url="/userprofile/login/")
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = { 'article': article, 
        'article_post_form': article_post_form,
        'columns' :columns,
        }
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)

blogApp/templates/article/create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">请选择栏目...</option>
                        {% for column in columns %}
                        <option value="{{column.id}}">{{column}}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags"
                    >
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" class="form-control" id="body" name="body"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

blogApp/templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{$ block title %}
文章详情
{% endblock}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{article.title}}</h1>
            <div class="col-12 alert alert-success">
                <div>作者：{{article.author}}
                    {% if user == article.author %}
                    · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                    · <a href="{% url 'article:article_update' article.id %}">
                        编辑文章
                    </a>
                    {% endif %}
                </div>
                <div>
                    浏览：{{article.total_views}}
                </div>
            </div>
            <!-- 新增一个隐藏表单 -->
            <form style="display:none" id="safe_delete" action="{%url 'article:article_safe_delete' article.id %}"
                method="POST">
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
            <div class="col-12">
                <p>{{article.body|safe}}</p>
            </div>
            <hr>
            {% if user.is_authenticated %}
            <div>
                <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>我也要发言：</strong>
                        </label>
                        <div>
                            {{comment_form.media}}
                            {{comment_form.body}}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">发送</button>
                </form>
            </div>
            {% else %}
            <br>
            <h5 class="row justify-content-center">
                请<a href="{% url 'userprofile:login' %}">登录</a>后回复
            </h5>
            <br>
            {% endif %}
            <h4>共有{{comments.count}}条评论</h4>
            <div>
                {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color:pink">
                        {{comment.user}}
                    </strong>于
                    <span style="color: green;">
                        {{comment.created|date:"Y-m-d H:i:s"}}
                    </span>时说：
                </p>
                <div style="font-family: inherit; font-size: 1em;">
                {{comment.body|safe}}
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- 目录 -->
        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{toc|safe}}
            </div>
        </div>
    </div>
</div>
<script>
    // 通过jq选择器找到隐藏的表单，并点击发送按钮，表单发起POST请求，并携带csrf令牌，避免csrf攻击
    function confirm_safe_delete() {
        layer.open({
            title: "确认删除",
            content: "确认删除这篇文章吗？",
            yes: function (index, layero) {
                $('form#safe_delete button').click()
                layer.close(index)
            }
        })
    }
</script>
{% endblock %}

blogApp/templates/article/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
首页
{% endblock %}

{% block content %}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?serach='{{search}}'">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search='{{search}}'">
                    最热
                </a>
            </li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章···" required>
            </form>
        </div>
    </div>
    {% if search %}
    {% if articles %}
    <h4><span style="color:red">"{{search}}"</span>的搜索结果</h4>
    <hr>
    {% else %}
    <h4>暂无<span style="color:red">"{{search}}"</span>有关的文章。</h4>
    <hr>
    {% endif %}
    {% endif %}
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 标题图 -->
        {% if article.avatar %}
        <div class="col-3">
            <img src="{{article.avatar.url}}" alt="avatar" style="max-width: 100%;border-radius: 20px;">
        </div>
        {% endif %}
        <div class="col-9">
            {% if article.column %}
            <button type="button" class="btn btn-sm-mb-2
                {% if article.column.title == 'django' %}
                    btn-success
                {% elif article.column.title == 'java' %}
                    btn-danger
                {% elif article.column.title == 'html' %}
                    btn-warning
                {% endif %}">
                {{article.column}}
            </button>
            {% endif %}
            <span>
                {% for tag in article.tags.all %}
                <a href="{% url 'article:article_list'%}?tag={{tag}}" class="badge badge-secondary">
                    {{tag}}
                </a>
                {% endfor %}
            </span>
            <h4>
                <b>
                    <a href="{% url 'article:article_detail' article.id %}" style="color: black;">
                        {{ article.title }}
                    </a>
                </b>
            </h4>
            <div>
                <p style="color:gray">{{article.body|slice:'100'}}</p>
            </div>
            <p>
                <span style="color: green;">
                    {{article.total_views}}浏览 &nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: blue;">
                    {{article.created|date:'Y-m-d'}}发布 &nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: darkred;">
                    {{article.updated|date:'Y-m-d'}}更新
                </span>
            </p>
        </div>
        <hr style="width:100%">
        {% endfor %}
    </div>
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                {% if articles.has_previous %}
                <a href="?page=1&order={{order}}&search={{search}}&tag={{tag}}" class="btn btn-success">
                    &laquo; 1
                </a>
            </span>
            <span>...</span>
            <a href="?page={{articles.previous_page_number}}&order={{order}}&search={{search}}&tag={{tag}}"
                class="btn btn-secondary">
                {{articles.previous_page_number}}
            </a>
            {% endif %}
            <span class="current btn btn-danger btn-lg">
                {{articles.number}}
            </span>
            {% if articles.has_next %}
            <a href="?page={{articles.next_page_number}}&order={{order}}&search={{search}}&tag={{tag}}"
                class="btn btn-secondary">
                {{articles.next_page_number}}
            </a>
            <span>...</span>
            <a href="?page={{articles.paginator.num_pages}}&order={{order}}&search={{search}}&tag={{tag}}"
                class="btn btn-success">
                {{articles.paginator.num_pages}} &raquo;
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blogApp/templates/article/update.html
{% extends "base.html" %}
{% load static %}
{% block title %}
     更新文章
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
     <div class="col-12">
        <br>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">文章标题</label>
                <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">
            </div>
            <div class="form-group">
                <label for="column">栏目</label>
                <select class="form-control" id="column" name="column"> 
                    <option value="none">请选择栏目...</option>
                    {% for column in columns %}
                    <option value="{{column.id}}"
                        {% if column.id == article.column.id %}
                            selected
                        {% endif %}
                    >
                    {{column}}
                </option>
                {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="body">文章正文</label>
                <textarea type="text" class="form-control" id="body" name="body" rows="12">{{article.body}}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">完成</button>
        </form>
     </div>
    </div>
</div>
{% endblock %}